"""employees rbac task tree srs intake

Revision ID: cfa0ea88bf91
Revises: 2039bcaf77a7
Create Date: 2026-08-13 03:12:34.248388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cfa0ea88bf91'
down_revision: Union[str, None] = '2039bcaf77a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MEMBER', name='user_role', create_type=False), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', name='invite_status'), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('user_skill_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=False),
    sa.Column('completed_task_count', sa.Integer(), nullable=False),
    sa.Column('completed_story_points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill', name='uq_user_skill_stats_user_skill')
    )
    op.add_column('backlog_items', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('backlog_items', sa.Column('assignee_id', sa.Uuid(), nullable=True))
    backlog_item_type_enum = postgresql.ENUM('EPIC', 'STORY', 'TASK', 'SUBTASK', name='backlog_item_type')
    backlog_item_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('backlog_items', sa.Column('item_type', backlog_item_type_enum, nullable=False, server_default='TASK'))
    op.add_column('backlog_items', sa.Column('story_points', sa.Integer(), nullable=True))
    op.add_column('backlog_items', sa.Column('required_skills', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('backlog_items', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'backlog_items', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'backlog_items', 'backlog_items', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('sprints', sa.Column('capacity_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('skills', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skills')
    op.drop_column('users', 'full_name')
    op.drop_column('sprints', 'capacity_points')
    op.drop_constraint(None, 'backlog_items', type_='foreignkey')
    op.drop_constraint(None, 'backlog_items', type_='foreignkey')
    op.drop_column('backlog_items', 'acceptance_criteria')
    op.drop_column('backlog_items', 'required_skills')
    op.drop_column('backlog_items', 'story_points')
    op.drop_column('backlog_items', 'item_type')
    postgresql.ENUM(name='backlog_item_type').drop(op.get_bind(), checkfirst=True)
    op.drop_column('backlog_items', 'assignee_id')
    op.drop_column('backlog_items', 'parent_id')
    op.drop_table('user_skill_stats')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
